# Generated by Django 4.1 on 2022-08-17 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Filters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filter_type', models.CharField(max_length=15, verbose_name='Тип фильтра (рабочая среда)')),
                ('external_diam', models.CharField(max_length=3, verbose_name='Наружный диаметр')),
                ('internal_diam', models.CharField(max_length=3, verbose_name='Внутренний диаметр')),
                ('length', models.CharField(max_length=4, verbose_name='Длина')),
                ('filter_material', models.CharField(max_length=15, verbose_name='Фильтрующий материал')),
                ('thickness', models.CharField(max_length=4, verbose_name='Тонкость фильтрации')),
                ('pressure', models.CharField(max_length=4, verbose_name='Давление')),
                ('end_filter', models.CharField(max_length=10, verbose_name='Тип торца')),
            ],
        ),
    ]
