# Generated by Django 4.1 on 2022-08-17 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('select_filter', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='filters',
            options={'verbose_name': 'Фильтр', 'verbose_name_plural': 'Фильтры'},
        ),
    ]
