# Generated by Django 4.1 on 2022-08-17 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('select_filter', '0002_alter_filters_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filters',
            name='filter_material',
            field=models.CharField(choices=[('orange', 'Oranges'), ('cantaloupe', 'Cantaloupes'), ('mango', 'Mangoes'), ('honeydew', 'Honeydews')], default='GF', max_length=15, verbose_name='Фильтрующий материал'),
        ),
    ]
