# Generated by Django 4.1 on 2022-08-18 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('select_filter', '0005_filters_seals_type_alter_filters_end_filter_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filters',
            name='seals_type',
            field=models.CharField(choices=[('FPM', 'FPM'), ('NBR', 'NBR'), ('PTFE', 'PTFE'), ('Без уплотнений', 'Без уплотнений')], max_length=20, verbose_name='Материал уплотнений фильтрующего элемента'),
        ),
    ]
